version: '3.8'
services:
  placenet-app:
    build:
      context: ./Placenet-App-Frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: placenet-app
    volumes:
      - ./Placenet-App-Frontend:/usr/src/app/placenet-app
      - /usr/src/app/placenet-app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 

volumes:
  postgres-data:
